# Generated by Django 4.1.1 on 2022-09-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='averagerating',
            field=models.FloatField(default=0),
        ),
    ]
